### ISSUE TITLE
Better layout for Gallery section

### ISSUE THREAD

**Issue by TechTonicShift** [ContriHUB/Enactus#1]
# 🚀Feature request

### Description
Following is the current layout of the gallery section:
![image](https://github.com/user-attachments/assets/84528a9a-7a43-4c74-bc88-14770d76857c)

You have to be creative and make a layout that amazes us. Points and bonus points for creativity will be rewarded accordingly.

### What more you have to implement?
Transition between images as we move between them and through them.

### The solution that we're looking for?
Something that is catchy and soothing to the eye.

**Comment by Ayush5071** [comment]
Sir @TechTonicShift ,can you please assign this issue to me .

**Comment by Ayush5071** [comment]
https://github.com/user-attachments/assets/4ccea4d7-6c5b-4a01-abf8-639de4c83002
see this if you like assign this issue to me.Also,let me know if wanna change something.

**Comment by TechTonicShift** [comment]
Actually I'm expecting a better UI than the one you provided @Ayush5071. The below is an example:
![image](https://github.com/user-attachments/assets/62eeeb6b-d2f5-4263-90b6-e0d54428afe9)

There will be photographs under the partition spaces and the photographs will be highlighted (come up in z axis) when we hover mouse cursor over them.
You have to also add smooth transitioning between images as we hover our cursor over them

**Comment by Ayush5071** [comment]
@TechTonicShift , sure sir i can create the same as you mentioned , please acccept my request to work on this ,if anyone else is not working on it RN.Also, i can design same layout as per Image but need more clarification on transition you want.

**Comment by TechTonicShift** [comment]
OK. I'll be accepting your request. For now on don't work on the transition part but just try to create the layout and the cursor hover effect. ATB!

**Comment by Ayush5071** [comment]
![Screenshot 2024-10-09 162618](https://github.com/user-attachments/assets/bfa24f1b-1fdf-42ed-b81c-d6bd4ad2486c)
sir is layout okay?

**Comment by Ayush5071** [comment]
@TechTonicShift

**Comment by TechTonicShift** [comment]
Can you send it in video format? @Ayush5071

**Comment by Ayush5071** [comment]
https://github.com/user-attachments/assets/9e55a8fa-3a15-4fad-ab98-e08e52d34018

**Comment by Ayush5071** [comment]
https://github.com/user-attachments/assets/b8fb6988-535b-471c-a54b-04b09e9ffd29

sir,This is final i also implemented dynamic rendering of image as before in this layout.

**Comment by Ayush5071** [comment]
@TechTonicShift

**Comment by TechTonicShift** [comment]
@Ayush5071 Great work. Just make sure to remove the dynamic rendering. Provide some margin from left and right. And add text (link) that says "More pictures.." which redirects the user to this URL. https://enactus-mnnit.netlify.app/gallery

**Comment by Ayush5071** [comment]
https://github.com/user-attachments/assets/2ed6cd13-f13e-4a35-8ad5-40cdbae6179f

Done sir i raised PR also added in Contrihub website

**Comment by Ayush5071** [comment]
@TechTonicShift I'm very comfortable now working with this codeBase , if there is any more issue or new feature to add please let me know.

**Comment by usha-here** [comment]
@TechTonicShift 
Good evening sir, I was assigned this issue through contrihub 2024 and below is my pull request so if you could please review it.
https://github.com/ContriHUB/Enactus/pull/3

**Comment by Ayush5071** [comment]
@TechTonicShift Sir, I raised a new PR, now there are no conflicts.

**Comment by TechTonicShift** [comment]
@Ayush5071 Your layout was well according to the requirement, hence your PR has been merged. @usha-here There will be more issues in the same repo so keep an eye for them.
