### ISSUE TITLE
Back button

### ISSUE THREAD

**Issue by TechTonicShift** [ContriHUB/Enactus#2]
# 🚀Feature Request
### Back button functionality to be implemented
Currently when we click on a project in website it shows up like this:
![image](https://github.com/user-attachments/assets/25957a7d-dcee-4264-be52-bea9f5674d61)

As you can see there is no back button available. Make a visually appealing button that will redirect you back to the project section of home page.

**Comment by Zish303** [comment]
@TechTonicShift I would like to work on this feature. Please assign it to me.

**Comment by PALLAVIKHEDLE** [comment]
Can you please assign it to me? It's pretty straight forward. I can easily knock out.

**Comment by Vaishnavi1047** [comment]
@TechTonicShift i want to work on this issue

**Comment by Manish-Sharma26** [comment]
@TechTonicShift 
I would like to work on it, can you assign it to me?

**Comment by TechTonicShift** [comment]
@Vaishnavi1047 You can start working on the issue. Make sure the button to match the theme of website. And do it for every project section. ATB!

**Comment by Vaishnavi1047** [comment]
![Screenshot 2024-10-09 140222](https://github.com/user-attachments/assets/1f518b4e-8b2a-4d03-bb54-88d30b7562d0)
@TechTonicShift  is it fine?

**Comment by Vaishnavi1047** [comment]
![Screenshot 2024-10-09 141124](https://github.com/user-attachments/assets/4feb5756-1586-4405-8f13-d8b82bc09056)
![Screenshot 2024-10-09 141133](https://github.com/user-attachments/assets/db8fcdd4-11c1-4417-b207-4a34ed1863f1)
bold or light?

**Comment by TechTonicShift** [comment]
Make it bold

**Comment by Vaishnavi1047** [comment]
![Screenshot 2024-10-09 150035](https://github.com/user-attachments/assets/a06672fc-32f5-45d1-a071-6bef8993b2cb)
i have added it in individual projects @TechTonicShift is it fine?
![Screenshot 2024-10-09 150048](https://github.com/user-attachments/assets/6323dea9-2bf0-42f0-83f6-747fbbd50f99)

**Comment by Vaishnavi1047** [comment]
@TechTonicShift can i make a pr?

**Comment by SaurabhChaudhary39** [comment]
@TechTonicShift may you assign this issue to me? I want to work on this issue.
